import { ArrowRight, Ruler, ShieldAlert } from "lucide-react";
import { Link } from "wouter";
import { SiteLayout, originalImages } from "@/components/SiteLayout";

const distances = [["Menos de 1", "0,2", "0,7"], ["13,8", "0,6", "1,6"], ["34,5", "0,9", "1,9"], ["69", "1,25", "2,25"], ["88", "1,55", "2,55"], ["138", "1,7", "3,7"], ["230", "1,8", "3,8"], ["440", "3,2", "5,2"], ["500", "5,2", "7,2"], ["700", "5,2", "7,2"]];

export default function DistanciaDaRede() {
  return <SiteLayout><section className="topic-hero green-hero"><div className="page-width"><div className="section-marker light-marker"><span>02</span><span>Guia de campo</span></div><div className="topic-hero-grid"><div><p className="eyebrow"><span className="eyebrow-line" /> Distância da rede</p><h1>Distância é <em>proteção.</em></h1></div><p>Não existe “só mais um pouquinho” quando o assunto é alta tensão. Use a tabela como referência e planeje o trabalho antes de se aproximar.</p></div></div></section><main className="page-width safety-page"><div className="safety-layout"><div className="safety-image"><img src={originalImages.distancia} alt="Fita métrica e cone de segurança próximos a uma rede elétrica" /><span className="image-note">A altura da máquina muda. A atenção não.</span></div><div className="safety-copy"><p className="section-kicker">01 / Antes de agir</p><h2>Olhe para cima. <em>Calcule o espaço.</em></h2><p>As distâncias abaixo indicam a zona de risco e a zona controlada a partir da rede. Na dúvida, interrompa a atividade e procure a distribuidora de energia.</p><div className="warning-line"><ShieldAlert size={19} /><span>Desligar um equipamento não elimina automaticamente o risco. Trate toda rede como energizada.</span></div></div></div><div className="distance-table-wrap"><div className="table-heading"><div><p className="section-kicker">02 / Referência rápida</p><h2>Quanto mais tensão, <em>mais espaço.</em></h2></div><Ruler size={27} /></div><div className="table-scroll"><table><thead><tr><th>Classe de tensão (kV)</th><th>Zona de risco (m)</th><th>Zona controlada (m)</th></tr></thead><tbody>{distances.map((row) => <tr key={row[0]}>{row.map((cell, index) => <td key={cell}>{index === 0 ? <strong>{cell}</strong> : cell}</td>)}</tr>)}</tbody></table></div><p className="table-footnote">Valores de referência adaptados do material original. Em operações profissionais, siga também as normas e procedimentos da sua empresa.</p></div><div className="do-not"><div className="do-not-item"><span>Não faça</span><p>Empinar pipas, usar ferramentas longas ou levantar caçambas perto de fios.</p></div><div className="do-not-item accent"><span>Faça</span><p>Observe o entorno, mantenha a distância e peça orientação antes de começar.</p></div></div><div className="next-topic"><span>Próximo tópico</span><Link href="/em-caso-de-acidente">Em caso de acidente <ArrowRight size={18} /></Link></div></main></SiteLayout>;
}
