import { ArrowUpRight, ExternalLink, Newspaper } from "lucide-react";
import { Link } from "wouter";
import { SiteLayout, originalImages } from "@/components/SiteLayout";

const stories = [
  { tag: "OBRA", title: "Pedreiro morre após tocar em fio de alta tensão", summary: "Em Balsas, no Maranhão, uma ferramenta de metal encostou na rede durante um trabalho em altura.", detail: "O impacto provocou uma queda de aproximadamente sete metros. A história reforça que ferramentas, estruturas e o próprio corpo precisam ficar afastados da rede.", image: originalImages.pedreiro, source: "Diário Sul Maranhense", url: "https://diariosulmaranhense.com.br/2021/03/27/balsas-pedreiro-morre-eletrocutado-em-fio-de-alta-tensao/" },
  { tag: "ANDAIME", title: "Trabalhador sofre descarga e cai de altura", summary: "Um trabalhador de 63 anos morreu após sofrer uma descarga elétrica e cair durante uma atividade em andaime.", detail: "O caso mostra como o risco elétrico se combina ao risco de queda. Antes de montar ou usar um andaime, observe os fios ao redor e mantenha a área isolada.", image: originalImages.andaime, source: "TNH1", url: "https://www.tnh1.com.br/noticia/nid/trabalhador-de-63-anos-morre-apos-sofrer-descarga-eletrica-e-cair-de-andaime-de-5-metros" },
  { tag: "CAMPO", title: "Máquina agrícola encosta na rede", summary: "Um operador de máquinas pesadas morreu durante um serviço de pulverização em Santa Maria das Barreiras, no Pará.", detail: "Máquinas altas e implementos agrícolas exigem planejamento do trajeto. Baixe a estrutura antes de circular e identifique a rede com antecedência.", image: originalImages.campo, source: "DOL", url: "https://dol.com.br/carajas/noticias/policia/689827/operador-de-maquina-morre-apos-receber-descarga-eletrica?d=1" },
  { tag: "VEÍCULOS", title: "Caçamba atinge fiação de alta tensão", summary: "Um motorista morreu após a caçamba do caminhão atingir a fiação em uma fazenda próxima a Nova Mutum.", detail: "Antes de bascular, olhe para cima. Se o veículo tocar na rede, permaneça dentro da cabine e aguarde o resgate — a menos que haja incêndio imediato.", image: originalImages.caminhao, source: "Portal Sorriso", url: "https://portalsorriso.com.br/noticia/qxc-motorista-de-caminhao-morre-eletrocutado-apos-cacamba-atingir-fiacao-de-alta-tensao-em-nova-mutum" },
];

export default function Historias() {
  return <SiteLayout><section className="topic-hero page-width"><div className="section-marker"><span>01</span><span>Arquivo de alertas</span></div><div className="topic-hero-grid"><div><p className="eyebrow dark-eyebrow"><span className="eyebrow-line" /> Histórias reais</p><h1>Um segundo muda a história. <em>O cuidado também.</em></h1></div><p>Relatos jornalísticos ajudam a enxergar situações que parecem comuns até o momento em que a rede elétrica entra em cena. Leia, reconheça o risco e compartilhe.</p></div></section><main className="page-width stories-page"><div className="stories-intro"><Newspaper size={19} /><span>04 relatos selecionados</span><span className="caption-dash" /><span>Fontes externas verificáveis</span></div><div className="stories-list">{stories.map((story, i) => <article className="story-row" key={story.title}><div className="story-image"><img src={story.image} alt="" /><span>{String(i + 1).padStart(2, "0")}</span></div><div className="story-content"><p className="story-tag">{story.tag}</p><h2>{story.title}</h2><p>{story.summary}</p><details><summary>O que este caso ensina</summary><p>{story.detail}</p></details><a className="source-link" href={story.url} target="_blank" rel="noreferrer">Ler fonte: {story.source} <ExternalLink size={14} /></a></div></article>)}</div><div className="next-topic"><span>Próximo tópico</span><Link href="/distancia-da-rede">Distância da rede <ArrowUpRight size={18} /></Link></div></main></SiteLayout>;
}
